config/routes.rb
MyculverhouseStock::Application.routes.draw do

  opinio_model

  root to: 'index#index'

  get "login" => 'login#new'
  post "login" => 'login#create'
  delete "logout" => 'login#destroy'

  get "password_resets/new" 
  get "/password_reset" => 'password_resets#new'
  get "/password_resets/:id/edit" => 'password_resets#edit'

  resources :password_resets do
    post 'edit' => :update
  end

  post "/action_items/:id" => "action_items#approve"
  resources :action_items

  get '/locations/labels/:id', to: "locations#label"
  resources :locations

  resources :publications

  resources :user_pictures

  resources :calendar_items

  resources :news_items

  resources :users

  resources :programs, :except => [:show,:edit]

  resources :departments, :except => [:show,:edit,:update]

  resources :centers, :except => [:show,:edit,:update]

  get "/calendar" => "master_calendar#index"
  post "/calendar" => "master_calendar#index"

  get "/news" => "news#index"
  post "/news" => "news#index"
  get "/news/:id" => "news#mark_as_blogged"

  get "/faculty" => "faculty#index"
  post "/faculty" => "faculty#index"

  get '/equipment/labels/:id', to: "equipment#label"
  resources :equipment

  post '/computer_program_associations/:equipmentID', to: "computer_program_associations#new"
  post '/computer_program_associations/uninstall/:equipmentID', to: "computer_program_associations#uninstall"

  resources :computer_program_associations, :only => [:index, :create, :update, :destroy, :show]

  post '/printer_associations/:equipmentID', to: "printer_associations#new"
  post '/printer_associations/uninstall/:equipmentID', to: "printer_associations#uninstall"
  resources :printer_associations, :only => [:index, :create, :update, :destroy, :show]

  get '/computer_programs/classroom', to: "computer_programs#classroom"
  get '/computer_programs/econ', to: "computer_programs#econ"
  get '/computer_programs/lab', to: "computer_programs#lab"
  get '/computer_programs/archived', to: "computer_programs#archived"
  resources :computer_programs

  post '/trouble_tickets/:id', to: "trouble_tickets#close"
  get "trouble_tickets/closed_tickets" => "trouble_tickets#closed_tickets"
  get "trouble_tickets/supervisor_tickets" => "trouble_tickets#supervisor_tickets"
  
  resources :trouble_tickets do
    member do
      post 'accept_ticket' => :accept_ticket
      opinio
    end
  end

  post '/lab_tickets/:id', to: 'lab_tickets#close'
  post '/lab_tickets/:labTicketID/new_task', to: "tasks#new"
  get '/lab_tickets/id', to: 'lab_tickets#show'
  get "lab_tickets/closed_tickets" => "lab_tickets#closed_tickets"
  resources :lab_tickets do
    member do
      opinio
    end
  end

  post '/tasks/:id', to: 'tasks#close'
  post '/tasks/:id/reopen', to: 'tasks#reopen'
  resources :tasks do
    member do
      opinio
    end
  end
  resources :tasks, :only => [:create, :update, :destroy, :show]

  post '/jobs/:ticketID', to: "jobs#new"
  post '/jobs/:ticketID/complete/:id', to: "jobs#complete"
  post '/jobs/:ticketID/reopen/:id', to: "jobs#reopen"
  resources :jobs, :only => [:create, :update, :destroy, :show]

  mount Monologue::Engine, at: '/blog' # or whatever path, be it "/blog" or "/monologue"

  ComfortableMexicanSofa::Routing.admin(:path => '/cms_admin')
  
  ComfortableMexicanSofa::Routing.content(:path => '/', :sitemap => false)

end

app/models/task.rb
class Task < ActiveRecord::Base
  #This allows us to manage task creation much more easily.  For a better explanation of how this is done, 
  #check out
  #http://railscasts.com/episodes/17-habtm-checkboxes
  has_and_belongs_to_many :equipment
  attr_accessible :assignedTech, :completed, :description, :labTicketID, :completed, :dateClosed, :closingTech
  
  #Adds opinio comment functionality to the model.
  opinio_subjectum
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :check_your_privilege

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  def closed_tickets
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
    @equipment = @task.equipment

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    @lab_ticket = LabTicket.find(params[:labTicketID])
    @lab_equipment = Equipment.where(locationID: @lab_ticket.locationID)
    @task.update_attributes(labTicketID: @lab_ticket.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    @lab_equipment = Equipment.where(locationID: LabTicket.find(@task.labTicketID).id)

  end

  def close
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.completed
        format.html { redirect_to @task, notice: 'Task is already complete.' }
        format.json { head :no_content }
      else
        if current_user.godBit or current_user.isSupervisor or current_user.isTech
          @task.update_attributes(completed: true)
          @task.update_attributes(dateClosed: Time.now())
          @task.update_attributes(closingTech: current_user.id)
          format.html { redirect_to @task, notice: 'Task has been completed successfully.' }
          format.json { head :no_content }
          #@task.send_task_close_burst
        else
          format.html { redirect_to @task, notice: 'You do not have sufficient permissions to close tickets.' }
          format.json { head :no_content }
        end
      end
    end
  end

  def reopen
    @task= Task.find(params[:id])
    respond_to do |format|
      if !@task.completed
        format.html { redirect_to @task, notice: 'Task is already open.' }
        format.json { head :no_content }
      else
        if current_user.godBit or current_user.isSupervisor or current_user.isTech
          @task.update_attributes(completed: false)
          format.html { redirect_to @task, notice: 'Task has been reopened successfully.' }
          format.json { head :no_content }
          #@task.send_task_close_burst
        else
          format.html { redirect_to @task, notice: 'You do not have sufficient permissions to reopen tickets.' }
          format.json { head :no_content }
        end
      end
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to "/lab_tickets/#{@task.labTicketID}", notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    #If the task is sending an equipment_ids hash, it reads it, otherwise it ensures the update action receives an empty equipment_ids hash.
    #Required for HABTM checkbox functionality.
    params[:task][:equipment_ids] ||= []
    @task = Task.find(params[:id])
    @task.equipment_ids = params[:task][:equipment_ids]

    respond_to do |format|
      if @task.update_attributes(task_params)
        #OK, yeah, I know this is lazy, but for some reason Create uses the Update action, and this is the best way to do this right now.
        format.html { redirect_to "/lab_tickets/#{@task.labTicketID}", notice: 'Task was successfully added/updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private

  def check_your_privilege
    if current_user.nil? 
      redirect_to(root_url)
    else
      unless current_user.godBit or current_user.isSuperUser or current_user.isSupervisorUser or current_user.isTechUser
        redirect_to(root_url)
      end
    end
  end


    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def task_params
      params.require(:task).permit(:assignedTech, :completed, :description, :labTicketID, :completed, :dateClosed, :closingTech)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%=simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form">
    <div>
      Description
      <%= f.input :description, :as => :text, :input_html => {:style => "width:510px", :rows => 5}, label: false%>
    </div>

    <div><p></p></div>

    <div>
      <%= f.label "Assigned Tech" %>
        <% if current_user.isTechUser %>
          <%= f.collection_select(:assignedTech, User.where(:id => current_user.id), :id, :formal_name)%>
        <%else%>
          <%= f.collection_select(:assignedTech, User.where(:isTechUser => 1), :id, :formal_name, :include_blank => false)%>
        <%end%>
    </div>

    <h3>Selected Equipment</h3>

    <div>
      <% @lab_equipment.each do |e| %>
        <p>
          <%= check_box_tag "task[equipment_ids][]", e.id, @task.equipment.include?(e) %>
          <%= e.digest %>
        </p>
      <% end %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

  </div>
<%end%>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<div><p></p></div>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table border=1>
  <tr>
    <th>Labticketid</th>
    <th>Description</th>
    <th>Assignedtech</th>
    <th>Completed</th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.labTicketID %></td>
    <td><%= task.description %></td>
    <td><%= User.find(task.assignedTech).formal_name %></td>
    <td><%= task.completed? %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lab Ticket:</b>
  <%= @task.labTicketID %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Assignedtech:</b>
  <%= User.find(@task.assignedTech).formal_name %>
</p>

<p>
  <b>Status:</b>
  <% if @task.completed %>
    <%= "Complete" %>
  <% else %>
    <%= "Incomplete" %>
  <% end %>
</p>

<p>
  <b>Equipment:</b>
</p>

<table border=1>
  <thead>
    <tr>
      <th>Type</th>
      <th>Description</th>
      <th>Serial Number</th>
      <th>Status</th>
      <th>Location</th>
      <th>Department</th>
    </tr>
  </thead>

  <tbody>


<% @equipment.each do |equipment| %>
    <tr>
      <tr class="spriteButton" onclick="document.location='<%=equipment_path(equipment.id)%>'" style="cursor:pointer">
      <td><%=equipment.type%></td>
      <td><%=equipment.description%></td>
      <td><%=equipment.serial%></td>
      <td><%=equipment.statusAlias%></td>
      <td><%=Location.find(equipment.locationID).name%></td>
      <td><%=Department.find(equipment.departmentID).name%></td>
    </tr>
  </tbody>
<% end %>
</table>

<div><p></p></div>

<div>
  <strong>Comments:</strong>
  <%= comments_for @task %>
</div>

<div><p></p></div>

<%= link_to '| Edit |', edit_task_path(@task) %> 
<%= link_to '| Back |', "/lab_tickets/#{@task.labTicketID}" %>
<%= link_to '| Close |', @task, :confirm => 'Are you sure?', :method => "close" %>