config/routes.rb
MyculverhouseStock::Application.routes.draw do

  opinio_model

  root to: 'index#index'

  get "login" => 'login#new'
  post "login" => 'login#create'
  delete "logout" => 'login#destroy'

  get "password_resets/new" 
  get "/password_reset" => 'password_resets#new'
  get "/password_resets/:id/edit" => 'password_resets#edit'

  resources :password_resets do
    post 'edit' => :update
  end

  post "/action_items/:id" => "action_items#approve"
  resources :action_items

  get '/locations/labels/:id', to: "locations#label"
  resources :locations

  resources :publications

  resources :user_pictures

  resources :calendar_items

  resources :news_items

  resources :users

  resources :programs, :except => [:show,:edit]

  resources :departments, :except => [:show,:edit,:update]

  resources :centers, :except => [:show,:edit,:update]

  get "/calendar" => "master_calendar#index"
  post "/calendar" => "master_calendar#index"

  get "/news" => "news#index"
  post "/news" => "news#index"
  get "/news/:id" => "news#mark_as_blogged"

  get "/faculty" => "faculty#index"
  post "/faculty" => "faculty#index"

  get '/equipment/labels/:id', to: "equipment#label"
  resources :equipment

  post '/computer_program_associations/:equipmentID', to: "computer_program_associations#new"
  post '/computer_program_associations/uninstall/:equipmentID', to: "computer_program_associations#uninstall"

  resources :computer_program_associations, :only => [:index, :create, :update, :destroy, :show]

  post '/printer_associations/:equipmentID', to: "printer_associations#new"
  post '/printer_associations/uninstall/:equipmentID', to: "printer_associations#uninstall"
  resources :printer_associations, :only => [:index, :create, :update, :destroy, :show]

  get '/computer_programs/classroom', to: "computer_programs#classroom"
  get '/computer_programs/econ', to: "computer_programs#econ"
  get '/computer_programs/lab', to: "computer_programs#lab"
  get '/computer_programs/archived', to: "computer_programs#archived"
  resources :computer_programs

  post '/trouble_tickets/:id', to: "trouble_tickets#close"
  get "trouble_tickets/closed_tickets" => "trouble_tickets#closed_tickets"
  get "trouble_tickets/supervisor_tickets" => "trouble_tickets#supervisor_tickets"
  
  resources :trouble_tickets do
    member do
      post 'accept_ticket' => :accept_ticket
      opinio
    end
  end

  post '/lab_tickets/:id', to: 'lab_tickets#close'
  post '/lab_tickets/:labTicketID/new_task', to: "tasks#new"
  get '/lab_tickets/id', to: 'lab_tickets#show'
  get "lab_tickets/closed_tickets" => "lab_tickets#closed_tickets"
  resources :lab_tickets do
    member do
      opinio
    end
  end

  post '/tasks/:id', to: 'tasks#close'
  post '/tasks/:id/reopen', to: 'tasks#reopen'
  resources :tasks do
    member do
      opinio
    end
  end
  resources :tasks, :only => [:create, :update, :destroy, :show]

  post '/jobs/:ticketID', to: "jobs#new"
  post '/jobs/:ticketID/complete/:id', to: "jobs#complete"
  post '/jobs/:ticketID/reopen/:id', to: "jobs#reopen"
  resources :jobs, :only => [:create, :update, :destroy, :show]

  mount Monologue::Engine, at: '/blog' # or whatever path, be it "/blog" or "/monologue"

  ComfortableMexicanSofa::Routing.admin(:path => '/cms_admin')
  
  ComfortableMexicanSofa::Routing.content(:path => '/', :sitemap => false)

end

app/models/publication.rb
class Publication < ActiveRecord::Base
  attr_accessible :facultyUserID, :publicationText
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_filter :check_your_privilege

  # GET /publications
  # GET /publications.json
  def index
    if current_user.isFacultyUser
      @publications = Publication.where(:facultyUserID == @faculty_user.id)
    elsif current_user.godBit or current_user.isCommunicationsUser
      @publications = Publication.all
    else
      @publications = Publication.none
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publications }
    end
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    @publication = Publication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/new
  # GET /publications/new.json
  def new
    @publication = Publication.new
    if current_user.isFacultyUser
      @faculty_user = User.find(current_user.id)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publication }
    end
  end


  # GET /publications/1/edit
  def edit
    @publication = Publication.find(params[:id])
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(params[:publication])

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render json: @publication, status: :created, location: @publication }
      else
        format.html { render action: "new" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publications/1
  # PUT /publications/1.json
  def update
    @publication = Publication.find(params[:id])

    respond_to do |format|
      if @publication.update_attributes(params[:publication])
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url }
      format.json { head :no_content }
    end
  end

  def check_your_privilege
    if current_user.nil? 
      redirect_to(root_url)
    else
      unless current_user.godBit or current_user.isSuperUser or current_user.isFacultyUser
        redirect_to(root_url)
      end
    end
  end

end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%if current_user.godBit or current_user.isSuperUser %>
    <div class="field">
      <%= f.label "Faculty Member:" %>
      <%= f.collection_select(:facultyUserID, User.where(:isFacultyUser => true), :id, :formal_name, :include_blank => true) %>
    </div>
  <%else%>
    <div class="field">
      <%= f.hidden_field :facultyUserID, :value=> @faculty_user.id,:readonly=>true%>
    </div>
  <%end%>

  <div class="field">
    <%= f.label :publicationText %><br />
    <%= f.text_area :publicationText %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<h1>Listing Publications</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Publication</th>
  </tr>

<% @publications.each do |publication| %>
  <tr>
    <td><%= User.find(publication.facultyUserID).formal_name %></td>
    <td><%= publication.publicationText %></td>
    <td><%= link_to 'View', publication %></td>
    <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
    <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render 'form' %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p>
  <b>Publication Text:</b>
  <%= @publication.publicationText %>
</p>


<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>