config/routes.rb
MyculverhouseStock::Application.routes.draw do

  opinio_model

  root to: 'index#index'

  get "login" => 'login#new'
  post "login" => 'login#create'
  delete "logout" => 'login#destroy'

  get "password_resets/new" 
  get "/password_reset" => 'password_resets#new'
  get "/password_resets/:id/edit" => 'password_resets#edit'

  resources :password_resets do
    post 'edit' => :update
  end

  post "/action_items/:id" => "action_items#approve"
  resources :action_items

  get '/locations/labels/:id', to: "locations#label"
  resources :locations

  resources :publications

  resources :user_pictures

  resources :calendar_items

  resources :news_items

  resources :users

  resources :programs, :except => [:show,:edit]

  resources :departments, :except => [:show,:edit,:update]

  resources :centers, :except => [:show,:edit,:update]

  get "/calendar" => "master_calendar#index"
  post "/calendar" => "master_calendar#index"

  get "/news" => "news#index"
  post "/news" => "news#index"
  get "/news/:id" => "news#mark_as_blogged"

  get "/faculty" => "faculty#index"
  post "/faculty" => "faculty#index"

  get '/equipment/labels/:id', to: "equipment#label"
  resources :equipment

  post '/computer_program_associations/:equipmentID', to: "computer_program_associations#new"
  post '/computer_program_associations/uninstall/:equipmentID', to: "computer_program_associations#uninstall"

  resources :computer_program_associations, :only => [:index, :create, :update, :destroy, :show]

  post '/printer_associations/:equipmentID', to: "printer_associations#new"
  post '/printer_associations/uninstall/:equipmentID', to: "printer_associations#uninstall"
  resources :printer_associations, :only => [:index, :create, :update, :destroy, :show]

  get '/computer_programs/classroom', to: "computer_programs#classroom"
  get '/computer_programs/econ', to: "computer_programs#econ"
  get '/computer_programs/lab', to: "computer_programs#lab"
  get '/computer_programs/archived', to: "computer_programs#archived"
  resources :computer_programs

  post '/trouble_tickets/:id', to: "trouble_tickets#close"
  get "trouble_tickets/closed_tickets" => "trouble_tickets#closed_tickets"
  get "trouble_tickets/supervisor_tickets" => "trouble_tickets#supervisor_tickets"
  
  resources :trouble_tickets do
    member do
      post 'accept_ticket' => :accept_ticket
      opinio
    end
  end

  post '/lab_tickets/:id', to: 'lab_tickets#close'
  post '/lab_tickets/:labTicketID/new_task', to: "tasks#new"
  get '/lab_tickets/id', to: 'lab_tickets#show'
  get "lab_tickets/closed_tickets" => "lab_tickets#closed_tickets"
  resources :lab_tickets do
    member do
      opinio
    end
  end

  post '/tasks/:id', to: 'tasks#close'
  post '/tasks/:id/reopen', to: 'tasks#reopen'
  resources :tasks do
    member do
      opinio
    end
  end
  resources :tasks, :only => [:create, :update, :destroy, :show]

  post '/jobs/:ticketID', to: "jobs#new"
  post '/jobs/:ticketID/complete/:id', to: "jobs#complete"
  post '/jobs/:ticketID/reopen/:id', to: "jobs#reopen"
  resources :jobs, :only => [:create, :update, :destroy, :show]

  mount Monologue::Engine, at: '/blog' # or whatever path, be it "/blog" or "/monologue"

  ComfortableMexicanSofa::Routing.admin(:path => '/cms_admin')
  
  ComfortableMexicanSofa::Routing.content(:path => '/', :sitemap => false)

end

app/models/lab_ticket.rb
class LabTicket < ActiveRecord::Base
  #Don't know why this comment is here.
  #has_and_belongs_to_many :tasks

  #This may not work as intended.
  has_many :tasks

  attr_accessible :clientID, :dateScheduled, :locationID, :problemDescription, :programID, :receivingTech, :requestedBy, :resolution, :status, :supervisorID, :techNotes, :urgency, :dateClosed, :closingTech
  
  #Adds opinio comment functionality to the model.
  opinio_subjectum

  def send_lab_ticket_close_burst
    #Mailer sends the client a notification that their ticket has been closed which includes a link to a google form with an exit survey.
    LabTicketMailer.lab_ticket_notify_client_of_close(self).deliver
    #Fires the unsubscribe_from_thread method.
    #unsubscribe_from_thread(self)
    #close_thread(self)
  end

  def status_alias
    #Returns a string representation of a given status for rendering in a view.  You can add more status types
    #by defining them here.
    if self.status==1 then
      "Open"
    elsif self.status==2 then
      "Deployed"
    elsif self.status==3 then
      "Awaiting Hardware"
    elsif self.status==4 then
      "Awaiting Client"
    elsif self.status==5 then
      "Outsourced"
    elsif self.status==6 then
      "On Hold"
    end
  end

  def digest
    #Returns an easy to read output representing the LabTicket.
    "ID##{self.id} - #{self.problemDescription}"
  end
end

app/controllers/lab_tickets_controller.rb
class LabTicketsController < ApplicationController

  before_filter :check_your_privilege
  before_filter :set_lab_ticket, only: [:show,:edit,:update,:destroy,:closed_tickets]

  # GET /lab_tickets
  # GET /lab_tickets.json
  def index
    @lab_tickets = LabTicket.order(:created_at)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lab_tickets }
    end
  end

  def closed_tickets
    @lab_tickets = LabTicket.order(:dateClosed)
  end

  # GET /lab_tickets/1
  # GET /lab_tickets/1.json
  def show
    @lab_ticket = LabTicket.find(params[:id])
    @tasks = Task.where(labTicketID: @lab_ticket.id)
    @lab_equipment = Equipment.where(locationID: @lab_ticket.locationID)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lab_ticket }
    end
  end

  # GET /lab_tickets/new
  # GET /lab_tickets/new.json
  def new
    @lab_ticket = LabTicket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lab_ticket }
    end
  end

  #GET "lab_tickets/:id/new_task" => "lab_tickets#new_task"
  def new_task
    @lab_ticket = LabTicket.find(params[:id])
    @task = Task.new
    @task.update_attributes(labTicketID: @lab_ticket.id)
  end

  # GET /lab_tickets/1/edit
  def edit
    @lab_ticket = LabTicket.find(params[:id])
  end

  def close
    @lab_ticket = LabTicket.find(params[:id])
    respond_to do |format|
      if @lab_ticket.status == 0
        format.html { redirect_to @lab_ticket, notice: 'Lab ticket is already closed.' }
        format.json { head :no_content }
      else
        if current_user.godBit or current_user.isSupervisor or current_user.isTech
          #Begin pre-close completeness check.
          if @lab_ticket.resolution.empty?
            format.html { redirect_to @lab_ticket, notice: 'Please enter a resolution for this ticket.' }
            format.json { head :no_content }
          else
            @lab_ticket.update_attributes(:dateClosed => Time.now())
            @lab_ticket.update_attributes(:closingTech => current_user.id)
            @lab_ticket.update_attributes(:status => 0)
            format.html { redirect_to @lab_ticket, notice: 'Lab ticket has been closed successfully.' }
            format.json { head :no_content }
            @lab_ticket.send_lab_ticket_close_burst
          end
        else
          format.html { redirect_to @lab_ticket, notice: 'You do not have sufficient permissions to close tickets.' }
          format.json { head :no_content }
        end
      end
    end
  end

  # POST /lab_tickets
  # POST /lab_tickets.json
  def create
    @lab_ticket = LabTicket.new(lab_ticket_params)

    respond_to do |format|
      if @lab_ticket.save
        format.html { redirect_to @lab_ticket, notice: 'Lab ticket was successfully created.' }
        format.json { render json: @lab_ticket, status: :created, location: @lab_ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @lab_ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_task
    @task = Task.create!(params[:task])
    flash[:notice] = "Task added."
    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /lab_tickets/1
  # PATCH/PUT /lab_tickets/1.json
  def update
    @lab_ticket = LabTicket.find(params[:id])

    respond_to do |format|
      if @lab_ticket.update_attributes(lab_ticket_params)
        format.html { redirect_to @lab_ticket, notice: 'Lab ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lab_ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lab_tickets/1
  # DELETE /lab_tickets/1.json
  def destroy
    @lab_ticket = LabTicket.find(params[:id])
    @lab_ticket.destroy

    respond_to do |format|
      format.html { redirect_to lab_tickets_url }
      format.json { head :no_content }
    end
  end

  private

  def check_your_privilege
    if current_user.nil? 
      redirect_to(root_url)
    else
      unless current_user.godBit or current_user.isSuperUser or current_user.isSupervisorUser or current_user.isTechUser
        redirect_to(root_url)
      end
    end
  end

  # Use this method to whitelist the permissible parameters. Example:
  # params.require(:person).permit(:name, :age)
  # Also, you can specialize this method with per-user checking of permissible attributes.
  def lab_ticket_params
    params.require(:lab_ticket).permit(:clientID, :dateScheduled, :locationID, :problemDescription, :programID, :receivingTech, :requestedBy, :resolution, :status, :supervisorID, :techNotes, :urgency)
  end


  def set_lab_ticket
    #Basically a throw/catch to pass an empty ticket to the controller if no ticket is passed to the controller otherwise.
    begin
      @lab_ticket = LabTicket.find(params[:id])
    rescue 
      @lab_ticket = LabTicket.new
    end
  end
end

app/helpers/lab_tickets_helper.rb
module LabTicketsHelper
end

app/views/lab_tickets/_form.html.erb
<%= simple_form_for(@lab_ticket) do |f| %>
  <%= f.error_notification %>

  <div class="form">

    <div class="row">
        <div class="span3"><%= f.label "Client*" %>
                <%= f.collection_select(:clientID, User.where(:isClientUser => 1), :id, :formal_name, :include_blank => true) %>
        </div>

        <div class="span3"><%= f.label "Location*" %>
            <%= #f.collection_select syntax:
            #f.collection_select(:paramYouWantToAssign,Collection.all,:thingYouWantToAssignToParam,:thingYouWantFormToDisplay,:options)
            f.collection_select(:locationID, Location.all, :id, :name, :include_blank => true) %>
        </div>
    </div>

    <div class="row">
        <div class="span3">
            <%= f.label "Receiving Tech*" %>
                <% if current_user.isTechUser %>
                    <%= f.collection_select(:receivingTech, User.where(:id => current_user.id), :id, :formal_name)%>
                <%else%>
                    <%= f.collection_select(:receivingTech, User.where(:isTechUser => 1), :id, :formal_name, :include_blank => true)%>
                <%end%>
        </div>

        <div class="span3">
            <%= f.label "Status*" %>
            <%= f.text_field :status 
                f.select :status, [['Open',1],['Deployed',2],['Awaiting Hardware',3],['Awaiting Client',4],['Outsourced',5],['On Hold',6]]
            %>
        </div>

    <div class="row">
        <div class="span3">
            <%= f.label "Program" %>
            <%= f.collection_select(:programID, ComputerProgram.all, :id, :digest, :include_blank => true) %>
        </div>

        <div class="span3">
            <%= f.label "Urgency*" %>
            <%= f.text_field :urgency 
                f.select :urgency, [['5',5],['4',4],['3',3],['2',2],['1',1]]
            %>
        </div>

        <div class="span3">
            <%= f.label "Supervisor" %>
            <%= f.collection_select(:supervisorID, User.where(:isSupervisorUser => 1), :id, :formal_name, :include_blank => true) %>
        </div>
    </div>

    <div class="row">
        <div class="span3">
            <%= f.input :problemDescription, :as => :text, :input_html => {:style => "width:510px", :rows => 5}, :label => "Problem Description*" %>
        </div>

        <div class="span3">
        </div>

        <div class="span3">
        </div>
    </div>


    <%= f.label "Date Scheduled" %>
    <%= f.datetime_select :dateScheduled,
        :include_blank => true,
        :selected => false
        %>

    <%= f.input :resolution, :as => :text, :input_html => {:style => "width:1125px", :rows => 6}, :label => "Resolution" %>

  </div>

<div class="actions">
  <%= f.button :submit %>
</div>
 
<% end %>

app/views/lab_tickets/_task_form.html.erb
<%=form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form">

    <div class="row">
        <div class="span3">
            <%= f.input :problemDescription, :as => :text, :input_html => {:style => "width:510px", :rows => 5}, :label => "Description" %>
        </div>
    </div>

    <div class="row">
      <div class="span3">
          <%= f.label "Assigned Tech" %>
              <% if current_user.godBit or current_user.isSuperUser or current_user.isSupervisorUser %>
                  <%= f.collection_select(:assignedTech, User.where(:isTechUser => 1), :id, :formal_name, :include_blank => false)%>
              <%else%>
                  <%= f.collection_select(:assignedTech, User.where(:id => current_user.id), :id, :formal_name)%>
              <%end%>
          <%end%>
      </div>
    </div>

    <div class="field">
      <%= f.hidden_field :labTicketID, value: @lab_ticket.id%>
    </div>

  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
  

app/views/lab_tickets/closed_tickets.html.erb
<h1>Closed Tickets</h1>

<table border=1>
	<th>Ticket ID</th>
	<th>Date Closed</th>
	<th>Status</th>
	<th>Closing Technician</th>
	<th>Client</th>
	<th>Resolution</th>


<!--Should omit open tickets-->
	<% LabTicket.all.each do |ticket| %>

	<!--Best practice seems to dictate that this conditional logic be handled by a helper.  I'm not sure how to use helpers, so I'm going to do this for the time being.-->
		<% if ticket.status==1 then %>
			<%next%>	<!--Skips open tickets-->
		<% else %>
			<tr bgcolor="#00FFFF" class="spriteButton" onclick="document.location='<%=trouble_ticket_path(ticket.id)%>'" style="cursor:pointer">
		<%end%>
				<td><%= ticket.id %></a></td>
				<td><%= ticket.dateClosed ? ticket.dateClosed.in_time_zone("Central Time (US & Canada)") : "--/--/----" %></td> 
				<td>Closed</td>
				<td><%=User.find(ticket.closingTech).formal_name %></td>
				<td><%= User.find(ticket.clientID).formal_name %></td>
				<td><%= ticket.resolution %></td>
			</tr>
	<%end%>
</table>

<div><p></p></div>

<%= link_to lab_ticket_path(:new) do %>| New Lab Ticket |<%end%> <%= link_to "| Open Lab Tickets |", :controller => "lab_tickets", :action => "index"%> 

app/views/lab_tickets/edit.html.erb
<h1>Editing lab_ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @lab_ticket %> |
<%= link_to 'Back', lab_tickets_path %>

app/views/lab_tickets/index.html.erb
<h1>Lab Tickets</h1>

<table border=1>
    <th>Ticket ID</th>
    <th>Date Created</th>
    <th>Status</th>
    <th>Client</th>
    <th>Problem</th>

    <% LabTicket.all.each do |ticket| %>

    <!--Best practice seems to dictate that this conditional logic be handled by a helper.  I'm not sure how to use helpers, so I'm going to do this for the time being.-->
        <% if ticket.status==0 then %>
            <%next%>    <!--Skips closed tickets-->
        <% elsif ticket.urgency.between?(1,2) then %>
            <tr bgcolor="#00FF00" class="spriteButton" onclick="document.location='<%=lab_ticket_path(ticket.id)%>'" style="cursor:pointer">
        <% elsif ticket.urgency.between?(3,4) then %>
            <tr bgcolor="#FFFF00" class="spriteButton" onclick="document.location='<%=lab_ticket_path(ticket.id)%>'" style="cursor:pointer">
        <% elsif ticket.urgency == 5 then%>
            <tr bgcolor="#FF0000" class="spriteButton" onclick="document.location='<%=lab_ticket_path(ticket.id)%>'" style="cursor:pointer">
        <% elsif ticket.urgency==0 then%>
            <tr bgcolor="#6D6D70" class="spriteButton" onclick="document.location='<%=lab_ticket_path(ticket.id)%>'" style="cursor:pointer">
        <% else %>
            <tr class="spriteButton" onclick="document.location='<%=lab_ticket_path(ticket.id)%>'" style="cursor:pointer">
        <%end%>
                
                <td><%= ticket.id %></a></td>
                <td><%= ticket.created_at.in_time_zone("Central Time (US & Canada)") %></td>
                
                <!--BEGIN TICKET STATUS FORMATTING BLOCK-->
                <% if ticket.status==1 then %>
                    <td>Open</td>
                <% elsif ticket.status==2 then %>
                    <td>Deployed</td>
                <% elsif ticket.status==3 then %>
                    <td>Awaiting Hardware</td>
                <% elsif ticket.status==4 then %>
                    <td>Awaiting Client</td>
                <% elsif ticket.status==5 then %>
                    <td>Outsourced</td>
                <% elsif ticket.status==6 then %>
                    <td>On Hold</td>
                <% else %>
                    <%next%>
                <%end%>
                <!--END TICKET STATUS FORMATTING BLOCK-->

                <td><%= User.find(ticket.clientID).formal_name %></td> 
                <td><%= ticket.problemDescription %></td>
            </tr>
    <%end%>
</table>

<div><p></p></div>

<%= link_to lab_ticket_path(:new) do %>| New Lab Ticket |<%end%> <%= link_to "| Closed Lab Tickets |", :controller => "lab_tickets", :action => "closed_tickets"%> 

app/views/lab_tickets/new.html.erb
<h1>New lab_ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', lab_tickets_path %>

app/views/lab_tickets/new_task.html.erb
<h1>New task for @lab_ticket.id</h1>

<%= render 'task_form' %>

<%= link_to 'Back', "/lab_tickets/#{@lab_ticket.id}" %>

app/views/lab_tickets/show.html.erb
<body>

<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= Location.find(@lab_ticket.locationID).name %>
</p>

<p>
  <b>Program:</b>
  <%if @lab_ticket.programID %>
    <%= Program.find(@lab_ticket.programID).name %>
  <%else%>
    <%="Not associated with a program."%>
  <%end%>
</p>

<p>
  <b>Problem Description:</b>
  <%= @lab_ticket.problemDescription %>
</p>

<p>
  <b>Status:</b>
  <%= @lab_ticket.status_alias %>
</p>

<p>
  <b>Date Scheduled:</b>
  <%if @lab_ticket.dateScheduled %>
    <%= @lab_ticket.dateScheduled %>
  <%else%>
    <%= "Not scheduled." %>
  <%end%>
</p>

<p>
  <b>Client:</b>
  <%= User.find(@lab_ticket.clientID).formal_name %>
</p>

<p>
  <b>Requested By:</b>
  <%if @lab_ticket.requestedBy %>
    <%= User.find(@lab_ticket.requestedBy).formal_name %>
  <%else%>
    <%= "This ticket was not requested by a user." %>
  <%end%>
</p>

<p>
  <b>Receiving Tech:</b>
  <%= User.find(@lab_ticket.receivingTech).formal_name %>
</p>

<p>
  <b>Supervisor:</b>
  <%if @lab_ticket.dateScheduled %>
    <%= User.find(@lab_ticket.supervisorID).formal_name %>
  <%else%>
    <%="No supervisor assigned."%>
  <%end%>
</p>

<p>
  <b>Tech Notes:</b>
  <%= @lab_ticket.techNotes %>
</p>

<p>
  <b>Urgency:</b>
  <%= @lab_ticket.urgency %>
</p>

<p>
  <b>Resolution:</b>
  <%= @lab_ticket.resolution %>
</p>

<%= link_to '| Edit |', edit_lab_ticket_path(@lab_ticket) %> 

<%if @tasks.count !=0%>
  <table border=1>
    <thead>
      <tr>
        <h5>Open Tasks</h5>
      </tr>

      <tr>
        <th>Task ID</th>
        <th>Date Created</th>
        <th>Description</th>
        <th>Technician</th>
      </tr>
    </thead>

    <tbody>
    <% @tasks.each do |t| %>
      <% if !t.completed %>
        <tr class="spriteButton" onclick="document.location='<%=task_path(t.id)%>'" style="cursor:pointer">
          <td><%= t.id %></a></td>
          <td><%= t.created_at.in_time_zone("Central Time (US & Canada)") %></td>
          <td><%= t.description %></td>
          <td><%= User.find(t.assignedTech).formal_name %></td>
        </tr>   
      <%end%>
    <%end%>
<%end%>

<%if @tasks.count !=0%>
  <table border=1>
    <thead>
      <tr>
        <h5>Closed Tasks</h5>
      </tr>

      <tr>
        <th>Task ID</th>
        <th>Date Created</th>
        <th>Description</th>
        <th>Technician</th>
      </tr>
    </thead>

    <tbody>
    <% @tasks.each do |t| %>
      <% if t.completed %>
        <tr class="spriteButton" onclick="document.location='<%=task_path(t.id)%>'" style="cursor:pointer">
          <td><%= t.id %></a></td>
          <td><%= t.created_at.in_time_zone("Central Time (US & Canada)") %></td>
          <td><%= t.description %></td>
          <td><%= User.find(t.assignedTech).formal_name %></td>
        </tr>   
      <%end%>
    </tbody>
    <%end%>
  </table>
<%end%>

<div><p></p></div>

<%= link_to '| Add A Task |', "/lab_tickets/#{@lab_ticket.id}/new_task", method: :post %></td>

<div><p></p></div>

<div>
  <strong>Comments:</strong>
  <%= comments_for @lab_ticket %>
</div>

<div><p></p></div>

<%= link_to '| Back |', lab_tickets_path %> <td>
<%= link_to '| Close |', @trouble_ticket, :confirm => 'Are you sure?', :method => "close" %> 
<%= link_to '| Delete |', @trouble_ticket, :confirm => 'Are you sure?', :method => :delete %>