config/routes.rb
MyculverhouseStock::Application.routes.draw do

  opinio_model

  root to: 'index#index'

  get "login" => 'login#new'
  post "login" => 'login#create'
  delete "logout" => 'login#destroy'

  get "password_resets/new" 
  get "/password_reset" => 'password_resets#new'
  get "/password_resets/:id/edit" => 'password_resets#edit'

  resources :password_resets do
    post 'edit' => :update
  end

  post "/action_items/:id" => "action_items#approve"
  resources :action_items

  get '/locations/labels/:id', to: "locations#label"
  resources :locations

  resources :publications

  resources :user_pictures

  resources :calendar_items

  resources :news_items

  resources :users

  resources :programs, :except => [:show,:edit]

  resources :departments, :except => [:show,:edit,:update]

  resources :centers, :except => [:show,:edit,:update]

  get "/calendar" => "master_calendar#index"
  post "/calendar" => "master_calendar#index"

  get "/news" => "news#index"
  post "/news" => "news#index"
  get "/news/:id" => "news#mark_as_blogged"

  get "/faculty" => "faculty#index"
  post "/faculty" => "faculty#index"

  get '/equipment/labels/:id', to: "equipment#label"
  resources :equipment

  post '/computer_program_associations/:equipmentID', to: "computer_program_associations#new"
  post '/computer_program_associations/uninstall/:equipmentID', to: "computer_program_associations#uninstall"

  resources :computer_program_associations, :only => [:index, :create, :update, :destroy, :show]

  post '/printer_associations/:equipmentID', to: "printer_associations#new"
  post '/printer_associations/uninstall/:equipmentID', to: "printer_associations#uninstall"
  resources :printer_associations, :only => [:index, :create, :update, :destroy, :show]

  get '/computer_programs/classroom', to: "computer_programs#classroom"
  get '/computer_programs/econ', to: "computer_programs#econ"
  get '/computer_programs/lab', to: "computer_programs#lab"
  get '/computer_programs/archived', to: "computer_programs#archived"
  resources :computer_programs

  post '/trouble_tickets/:id', to: "trouble_tickets#close"
  get "trouble_tickets/closed_tickets" => "trouble_tickets#closed_tickets"
  get "trouble_tickets/supervisor_tickets" => "trouble_tickets#supervisor_tickets"
  
  resources :trouble_tickets do
    member do
      post 'accept_ticket' => :accept_ticket
      opinio
    end
  end

  post '/lab_tickets/:id', to: 'lab_tickets#close'
  post '/lab_tickets/:labTicketID/new_task', to: "tasks#new"
  get '/lab_tickets/id', to: 'lab_tickets#show'
  get "lab_tickets/closed_tickets" => "lab_tickets#closed_tickets"
  resources :lab_tickets do
    member do
      opinio
    end
  end

  post '/tasks/:id', to: 'tasks#close'
  post '/tasks/:id/reopen', to: 'tasks#reopen'
  resources :tasks do
    member do
      opinio
    end
  end
  resources :tasks, :only => [:create, :update, :destroy, :show]

  post '/jobs/:ticketID', to: "jobs#new"
  post '/jobs/:ticketID/complete/:id', to: "jobs#complete"
  post '/jobs/:ticketID/reopen/:id', to: "jobs#reopen"
  resources :jobs, :only => [:create, :update, :destroy, :show]

  mount Monologue::Engine, at: '/blog' # or whatever path, be it "/blog" or "/monologue"

  ComfortableMexicanSofa::Routing.admin(:path => '/cms_admin')
  
  ComfortableMexicanSofa::Routing.content(:path => '/', :sitemap => false)

end

app/models/action_item.rb
class ActionItem < ActiveRecord::Base
  attr_accessible :createdByID, :isApproved, :itemType
end

app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
  ##
  #Handles the ActionItems queue, which allows approved users to screen events and news submitted by other users before it is
  #posted to outfacing pages.
  #
  #    Use case:
  #    
  #    ADMIN => ActionItem.approve => CalendarItem shows up on MasterCalendar.index
  #    ADMIN => ActionItem.approve => NewsItem shows up on News.index
  #
  ##


  #Ensures that only authorized users will be able to access the ActionItems controller methods.
  before_filter :check_your_privilege

  # GET /action_items
  # GET /action_items.json
  def index
    @action_items = ActionItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @action_items }
    end
  end

  # POST /action_items
  # POST /action_items.json
  def create
    @action_item = ActionItem.new(action_item_params)

    respond_to do |format|
      if @action_item.save
        format.html { redirect_to @action_item, notice: 'Action item was successfully created.' }
        format.json { render json: @action_item, status: :created, location: @action_item }
      else
        format.html { render action: "new" }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /action_items/1
  # PATCH/PUT /action_items/1.json
  def update
    @action_item = ActionItem.find(params[:id])

    respond_to do |format|
      if @action_item.update_attributes(action_item_params)
        format.html { redirect_to @action_item, notice: 'Action item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_items/1
  # DELETE /action_items/1.json
  def destroy
    @action_item = ActionItem.find(params[:id])
    
    #Determines the type of action item and enables it on the appropriate page.
    if @action_item.itemType == "news"
      @action_item_proper = NewsItem.where(actionItemID: @action_item.id).first
    elsif @action_item.itemType == "calendar"
      @action_item_proper = CalendarItem.where(actionItemID: @action_item.id).first
    end

    @action_item_proper.destroy
    @action_item.destroy

    respond_to do |format|
      format.html { redirect_to action_items_url }
      format.json { head :no_content }
    end
  end

  #Approval method.
  #Admins and communications users can approve action items.  Once approved, an action item will show up on the proper outfacing page.
  #Example- an approved CalendarItem will become visible on the Master_Calendar page.
  def approve
    respond_to do |format|
      @action_item=ActionItem.find(params[:id])
      if @action_item.isApproved
        @action_item.update_attributes(:isApproved => 0)
        format.html { redirect_to action: 'index', notice: 'Item has been unapproved successfully.' }
        format.json { head :no_content }
      else
        @action_item.update_attributes(:isApproved => 1)
        format.html { redirect_to action: 'index', notice: 'Item has been approved successfully.' }
        format.json { head :no_content }
      end
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def action_item_params
      params.require(:action_item).permit(:createdByID, :isApproved)
    end

    def check_your_privilege
      if current_user.nil? 
        redirect_to(root_url)
      else
        unless current_user.godBit or current_user.isSuperUser or current_user.isCommunicationsUser
          redirect_to(root_url)
        end
      end
    end
end

app/helpers/action_items_helper.rb
module ActionItemsHelper
end

app/views/action_items/_form.html.erb
<%= form_for(@action_item) do |f| %>
  <% if @action_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_item.errors.count, "error") %> prohibited this action_item from being saved:</h2>

      <ul>
      <% @action_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Created By:" %><br />
      <%= f.select :createdByID, [[User.find(@action_item.createdByID).formal_name, User.find(@action_item.createdByID).id]], :readonly => true%>
  </div>

  <div class="field">
    <%= f.label :isApproved %><br />
    <%= f.check_box :isApproved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/action_items/edit.html.erb
<h2>Editing action_item</h2>

<%= render 'form' %>

<%= link_to 'Show', @action_item %> |
<%= link_to 'Back', action_items_path %>

app/views/action_items/index.html.erb
<h2>Listing Action Items</h2>

<table border=1>
  <tr>
    <th>Created By:</th>
    <th>Item Type:</th>
    <th>Item Title:</th>
    <th>Item Text:</th>
    <th>Item Date:</th>
    <th>Approval Status:</th>
    <th></th>
    <th></th>
  </tr>

<% @action_items.each do |action_item| %>
  <tr>
    <td><%= User.find(action_item.createdByID).formal_name %></td>
    <td><%= action_item.itemType %></td>

    <%if action_item.itemType == "news"%>
      <td><%= NewsItem.find_by_actionItemID(action_item.id).title %></td>
      <td><%= NewsItem.find_by_actionItemID(action_item.id).newsText %></td>
    <%elsif action_item.itemType == "calendar"%>
      <td><%= CalendarItem.find_by_actionItemID(action_item.id).title %></td>
      <td><%= CalendarItem.find_by_actionItemID(action_item.id).calendarText %></td>
    <%end%>

    <%if action_item.itemType == "news"%>
      <td><%= NewsItem.where(:actionItemID == action_item.id).first.created_at %></td>
    <%elsif action_item.itemType == "calendar"%>
      <td><%= CalendarItem.where(:actionItemID == action_item.id).first.calendarDate %></td>
    <%end%>    
    
    <td><%= action_item.isApproved %></td>
    <td><%= link_to 'Destroy', action_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% if action_item.isApproved %>
      <td><%= link_to 'Unapprove', action_item, method: :approve, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
      <td><%= link_to 'Approve', action_item, method: :approve, data: { confirm: 'Are you sure?' } %></td>
    <%end%>
  </tr>
<% end %>
</table>

<br />

app/views/action_items/new.html.erb
<h2>New Action Item</h2>

<%= render 'form' %>

<%= link_to 'Back', action_items_path %>

app/views/action_items/show.html.erb
<p>
  <b>Created By:</b>
  <%= User.find(@action_item.createdByID).formal_name %>
</p>

<p>
  <b>Approved?</b>
  <%= @action_item.isApproved %>
</p>

<%if !current_user.blank?%>
	<%if current_user.godBit or current_user.isSuperUser or current_user.id == @action_item.createdByID%>
		<%= link_to 'Edit', edit_action_item_path(@action_item) %> |
	<%end%>
<%end%>

<%= link_to 'Back', action_items_path %>